insert into meals values (1,'Pancakes','breakfast','','','recipe',0);
insert into meals values (2,'Bulls Eye','breakfast','','','recipe',0);
insert into meals values (3,'Green Eggs and Ham','breakfast','','','recipe',0);
insert into meals values (4,'Cheese Eggs with onions and ham','breakfast','','','recipe',0);
insert into meals values (5,'Mexican Omelets','breakfast','','','recipe',0);
insert into meals values (6,'French toast','breakfast','','','recipe',0);
insert into meals values (7,'Cheese Toast','breakfast','','','recipe',0);
insert into meals values (8,'Cinnamon rolls','breakfast','','','recipe',0);
insert into meals values (9,'Fruit Kebabs','breakfast','','','recipe',0);
insert into meals values (10,'Monkey Bread','breakfast','','','recipe',0);
insert into meals values (11,'stone soup','lunch','','','recipe',0);
insert into meals values (12,'Fried Egg Sandwiches','lunch','','','recipe',0);
insert into meals values (13,'Egg Salid','lunch','','','recipe',0);
insert into meals values (14,'Cheese Quesadillas with salsa','lunch','','','recipe',0);
insert into meals values (15,'ambrosia salid','lunch','','','recipe',0);
insert into meals values (16,'Pizza','lunch','','','recipe',0);
insert into meals values (17,'Chicken pot pie','dinner','','','recipe',0);
insert into meals values (18,'Pasta with homemade sauce','dinner','','','recipe',0);
insert into meals values (19,'Pizza homemade','dinner','','','recipe',0);
insert into meals values (20,'spinach salid','dinner','','','recipe',0);
insert into meals values (21,'Baked potatoes','dinner','','','recipe',0);
