insert into meals values (1,'Pancakes','breakfast','','' ,0,null);
insert into meals values (2,'Bulls Eye','breakfast','','' ,0,null);
insert into meals values (3,'Green Eggs and Ham','breakfast','','' ,0,null);
insert into meals values (4,'Cheese Eggs with onions and ham','breakfast','','' ,0,null);
insert into meals values (5,'Mexican Omelets','breakfast','','' ,0,null);
insert into meals values (6,'French toast','breakfast','','' ,0,null);
insert into meals values (7,'Cheese Toast','breakfast','','' ,0,null);
insert into meals values (8,'Cinnamon rolls','breakfast','','' ,0,null);
insert into meals values (9,'Fruit Kebabs','breakfast','','' ,0,null);
insert into meals values (10,'Monkey Bread','breakfast','','' ,0,null);
insert into meals values (11,'stone soup','lunch','','' ,0,null);
insert into meals values (12,'Fried Egg Sandwiches','lunch','','' ,0,null);
insert into meals values (13,'Egg Salid','lunch','','' ,0,null);
insert into meals values (14,'Cheese Quesadillas with salsa','lunch','','' ,0,null);
insert into meals values (15,'ambrosia salid','lunch','','' ,0,null);
insert into meals values (16,'Pizza','lunch','','' ,0,null);
insert into meals values (17,'Chicken pot pie','dinner','','' ,0,null);
insert into meals values (18,'Pasta with homemade sauce','dinner','','' ,0,null);
insert into meals values (19,'Pizza homemade','dinner','','' ,0,null);
insert into meals values (20,'spinach salid','dinner','','' ,0,null);
insert into meals values (21,'Baked potatoes','dinner','','' ,0,null);
